name: form-to-1milion

services:
  pg:
    image: postgres:15
    container_name: form-to-1milion-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: form_to_1milion_db
    ports:
      - "5432:5432"
    networks:
      - form-net
    deploy:
      resources:
        limits:
          cpus: '0.60'      
          memory: 512M

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
    networks:
      - form-net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - form-net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana
    networks:
      - form-net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    depends_on:
      - prometheus

  api:
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    container_name: form-to-1milion-api
    depends_on:
      - pg
      - jaeger
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=pg
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=form_to_1milion_db
      - DB_SSLMODE=disable
    networks:
      - form-net
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 1G

  consumer:
    build:
      context: .
      dockerfile: ./cmd/worker/Dockerfile
    container_name: form-to-1milion-consumer
    depends_on:
      - pg
      - rabbitmq
      - jaeger
    environment:
      - DB_HOST=pg
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=form_to_1milion_db
      - DB_SSLMODE=disable
    networks:
      - form-net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M

  rabbitmq:
    image: rabbitmq:3-management
    container_name: form-to-1milion-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - form-net
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 2G

volumes:
  prometheus-data:
  grafana-data:

networks:
  form-net:
    driver: bridge

