name: form-to-1milion

services:
  pg:
    image: postgres:15
    container_name: form-to-1milion-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: form_to_1milion_db
    ports:
      - "5432:5432"
    networks:
      - form-net
    deploy:
      resources:
        limits:
          cpus: '0.60'      
          memory: 512M

  api:
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    container_name: form-to-1milion-api
    depends_on:
      - pg
    ports:
      - "8080"
    environment:
      - DB_HOST=pg
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=form_to_1milion_db
      - DB_SSLMODE=disable
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/form-to-1milion-queue
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-2
      - AWS_DEFAULT_REGION=us-east-2
      - AWS_ENDPOINT_URL=http://localstack:4566
    networks:
      - form-net
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 1G

  api2:
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    container_name: form-to-1milion-api2
    depends_on:
      - pg
    ports:
      - "8081"
    environment:
      - DB_HOST=pg
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=form_to_1milion_db
      - DB_SSLMODE=disable
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/form-to-1milion-queue
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-2
      - AWS_DEFAULT_REGION=us-east-2
      - AWS_ENDPOINT_URL=http://localstack:4566
    networks:
      - form-net
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 1G

  consumer:
    build:
      context: .
      dockerfile: ./cmd/worker/Dockerfile
    container_name: form-to-1milion-consumer
    depends_on:
      - pg
    environment:
      - DB_HOST=pg
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=form_to_1milion_db
      - DB_SSLMODE=disable
      - SQS_QUEUE_URL=http://localstack:4566/000000000000/form-to-1milion-queue
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-2
      - AWS_DEFAULT_REGION=us-east-2
      - AWS_ENDPOINT_URL=http://localstack:4566
    networks:
      - form-net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M

#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: form-to-1milion-rabbitmq
#    environment:
#      - RABBITMQ_DEFAULT_USER=user
#      - RABBITMQ_DEFAULT_PASS=password
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    networks:
#      - form-net
#    deploy:
#      resources:
#        limits:
#          cpus: '0.80'
#          memory: 2G

  localstack:
    image: localstack/localstack:3.8
    container_name: form-to-1milion-localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT=1
      - SQS_ENDPOINT_STRATEGY=path
      - HOSTNAME_EXTERNAL=localstack

    volumes:
      - "localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - form-net
    deploy:
      resources:
        limits:
          cpus: '10.00'
          memory: 4.5G

  #k6:
  #  image: grafana/k6
  #  container_name: k6-load-test
  #  volumes:
  #    - ./scenarios:/scripts
  #    - ./scenarios/reports:/reports
  #  working_dir: /scripts
  #  entrypoint: ["k6", "run", "load-teste.js"]
  #  depends_on:
  #    - nginx
  #  networks:
  #    - form-net
  #  deploy:
  #    resources:
  #      limits:
  #        cpus: '1.00'       # allow up to one full CPU core for load test
  #        memory: 1G         # limit memory to 1 gigabyte

  nginx:
    image: nginx:1.27-alpine
    container_name: form-to-1milion-nginx
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - form-net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

networks:
  form-net:
    driver: bridge

volumes:
  localstack-data:
