name: form-to-1milion CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672

    env:
      DB_HOST: localhost
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: testdb
      DB_PORT: 5432

      RABBITMQ_URL: amqp://guest:guest@localhost:5672/

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Cache de dependências
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Instalar dependências
        run: go mod download

      - name: Verificar formatação
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Código não formatado"
            gofmt -l .
            exit 1
          fi

      - name: Go Vet
        run: go vet ./...

      - name: Aguardar Postgres
        run: sleep 5

      - name: Rodar testes
        run: go test ./... -v -cover
